version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10.15.3
      - image: postgres:11.7-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: project_vacance_entre_amis_test

jobs:
  test_node:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test_node
